package com.test.db;
// Generated Jan 21, 2017 2:12:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Address generated by hbm2java
 */

@XmlRootElement(name="address")
@XmlSeeAlso({Parent.class})
public class Address implements java.io.Serializable {

	private Integer AId;
	private String streetName;
	private String district;
	private String city;
	private String state;
	private String pincode;
	private String country;
	private Date createdDate;
	private boolean isActive;
	@XmlElement(name="parents")
	private Set parents = new HashSet(0);

	public Address() {
	}

	public Address(String district, String city, String state, String pincode, String country, Date createdDate,
			boolean isActive) {
		this.district = district;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.country = country;
		this.createdDate = createdDate;
		this.isActive = isActive;
	}

	public Address(String streetName, String district, String city, String state, String pincode, String country,
			Date createdDate, boolean isActive, Set parents) {
		this.streetName = streetName;
		this.district = district;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.country = country;
		this.createdDate = createdDate;
		this.isActive = isActive;
		this.parents = parents;
	}

	public Integer getAId() {
		return this.AId;
	}

	public void setAId(Integer AId) {
		this.AId = AId;
	}

	public String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(String streetName) {
		this.streetName = streetName;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getParents() {
		return this.parents;
	}

	public void setParents(Set parents) {
		this.parents = parents;
	}

}
