package com.test.db;
// Generated Jan 21, 2017 2:12:31 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Barcode generated by hbm2java
 */

@XmlRootElement(name="barcode")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlSeeAlso({Item.class})
public class Barcode implements java.io.Serializable {

	private Integer BId;
	private String typeName;
	private String identifier;
	private boolean isActive;
	@XmlElement(name="items")
	private Set items = new HashSet(0);

	public Barcode() {
	}

	public Barcode(String typeName, String identifier, boolean isActive) {
		this.typeName = typeName;
		this.identifier = identifier;
		this.isActive = isActive;
	}

	public Barcode(String typeName, String identifier, boolean isActive, Set items) {
		this.typeName = typeName;
		this.identifier = identifier;
		this.isActive = isActive;
		this.items = items;
	}

	public Integer getBId() {
		return this.BId;
	}

	public void setBId(Integer BId) {
		this.BId = BId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
