package com.test.db;
// Generated Jan 21, 2017 2:12:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Item generated by hbm2java
 */
@XmlRootElement(name="item")
@XmlAccessorType(XmlAccessType.FIELD)
public class Item implements java.io.Serializable {

	private Integer itemId;
	@XmlTransient
	private Barcode barcode;
	@XmlTransient
	private Product product;
	private String itemName;
	private Date createdDate;
	private boolean isActive;

	public Item() {
	}

	public Item(Barcode barcode, Product product, String itemName, Date createdDate, boolean isActive) {
		this.barcode = barcode;
		this.product = product;
		this.itemName = itemName;
		this.createdDate = createdDate;
		this.isActive = isActive;
	}

	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public Barcode getBarcode() {
		return this.barcode;
	}

	public void setBarcode(Barcode barcode) {
		this.barcode = barcode;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

}
