package com.test.db;
// Generated Jan 21, 2017 2:12:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Parent generated by hbm2java
 */
@XmlRootElement(name="parent")
@XmlSeeAlso({Product.class})
public class Parent implements java.io.Serializable {

	private Integer paId;
	@XmlTransient
	private Address address;
	private String parentName;
	private String boss;
	private Date createdDate;
	private boolean isActive;
	@XmlElement(name="products")
	private Set products = new HashSet(0);

	public Parent() {
	}

	public Parent(Address address, String parentName, Date createdDate, boolean isActive) {
		this.address = address;
		this.parentName = parentName;
		this.createdDate = createdDate;
		this.isActive = isActive;
	}

	public Parent(Address address, String parentName, String boss, Date createdDate, boolean isActive, Set products) {
		this.address = address;
		this.parentName = parentName;
		this.boss = boss;
		this.createdDate = createdDate;
		this.isActive = isActive;
		this.products = products;
	}

	public Integer getPaId() {
		return this.paId;
	}

	public void setPaId(Integer paId) {
		this.paId = paId;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getBoss() {
		return this.boss;
	}

	public void setBoss(String boss) {
		this.boss = boss;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
