package com.test.db;
// Generated Dec 1, 2016 3:21:18 PM by Hibernate Tools 4.3.1.Final

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Person generated by hbm2java
 */
@XmlRootElement  
public class Person implements java.io.Serializable {

	private int id;
	private String name;
	private String email;
	private String country;
	
	public Person() {
	}


	public Person(int id, String name, String email, String country) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.country = country;
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public String getCountry() {
		return country;
	}


	public void setCountry(String country) {
		this.country = country;
	}


	@Override
	public String toString() {
		return "Person [id=" + id + ", name=" + name + ", email=" + email
				+ ", country=" + country + "]";
	}
	
}
