package com.test.db;
// Generated Jan 21, 2017 2:12:31 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer CId;
	private String categoryName;
	private Date createdDate;
	private Set products = new HashSet(0);

	public Category() {
	}

	public Category(String categoryName, Date createdDate) {
		this.categoryName = categoryName;
		this.createdDate = createdDate;
	}

	public Category(String categoryName, Date createdDate, Set products) {
		this.categoryName = categoryName;
		this.createdDate = createdDate;
		this.products = products;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
